{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm-rest-api.serviceAccountName" . }}
  labels:
    {{- include "helm-rest-api.labels" . | nindent 4 }}
{{- end }}
